
services:
  activemq:
    image: apache/activemq-classic:5.18.3
    container_name: activemq
    ports:
      - "61616:61616"   # JMS
      - "8161:8161"     # Web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin

  app:
    build: .
    container_name: optima360-app
    ports:
      - "8080:8080"
    environment:
      ACTIVEMQ_URL: tcp://activemq:61616
      ACTIVEMQ_USER: admin
      ACTIVEMQ_PASSWORD: admin
    depends_on:
      - activemq
