
server:
  port: 8080

spring:
  application:
    name: optima360-activemq
  activemq:
    broker-url: ${ACTIVEMQ_URL:tcp://localhost:61616}
    user: ${ACTIVEMQ_USER:admin}
    password: ${ACTIVEMQ_PASSWORD:admin}
  jms:
    pub-sub-domain: false

logging:
  level:
    root: INFO
